steps:
  - name: gcr.io/cloud-builders/docker
    id: docker
    timeout: 1000s
    args:
      - 'build'
      - '-t'
      - '${_REGISTRY}/${_CI_PROJECT_NAMESPACE}/${_CI_PROJECT_NAME}:${_TAG}'
      - '.'
images:
  - '${_REGISTRY}/${_CI_PROJECT_NAMESPACE}/${_CI_PROJECT_NAME}:${_TAG}'
timeout: 1800s
