include:
  - 'https://gitlab.com/smartive/open-source/gitlab-ci-templates/raw/master/templates.yml'
  - 'https://gitlab.com/smartive/open-source/gitlab-ci-templates/raw/master/preview-branches.yml'

stages:
  - build
  - deploy

build:
  extends: .gcb-docker
  stage: build
  variables:
    SUB_REGISTRY: $REGISTRY
    SUB_CI_PROJECT_NAMESPACE: $CI_PROJECT_NAMESPACE
    SUB_CI_PROJECT_NAME: $CI_PROJECT_NAME
    SUB_TAG: $CI_COMMIT_REF_SLUG

deploy preview:
  variables:
    APP_NAME: $CI_COMMIT_REF_SLUG
    KUBE_CONFIG: $DEV_KUBE_CONFIG
    REPLICAS: '1'
    TAG: $CI_COMMIT_REF_SLUG
    URL: $CI_COMMIT_REF_SLUG.preview.smartive.ch
  environment:
    url: https://$CI_COMMIT_REF_SLUG.preview.smartive.ch

stop preview:
  variables:
    APP_NAME: $CI_COMMIT_REF_SLUG
    KUBE_CONFIG: $DEV_KUBE_CONFIG
    REPLICAS: '1'
    TAG: $CI_COMMIT_REF_SLUG
    URL: $CI_COMMIT_REF_SLUG.preview.smartive.ch

deploy prod:
  extends: .k8s-deploy
  stage: deploy
  variables:
    APP_NAME: $CI_PROJECT_NAME
    CERT_ISSUER: letsencrypt-production
    KUBE_CONFIG: $PROD_KUBE_CONFIG
    REPLICAS: '2'
    TAG: $CI_COMMIT_REF_SLUG
    URL: smartive.ch
  environment:
    name: production
    url: https://smartive.ch
  only:
    - master
