include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'
  - project: 'smartive/ci-templates'
    ref: v4.0.0
    file: '/all-templates.yml'

.default_template:
  extends: .base
  image: node:21-alpine

.test_template:
  extends: .default_template
  image: mcr.microsoft.com/playwright:focal
  before_script:
    - npm ci

linting:
  extends: .default_template
  before_script:
    - npm ci
  script:
    - npm run lint
  only:
    - merge_requests

check unused code:
  extends: .default_template
  before_script:
    - npm ci
  script:
    - npm run knip
  only:
    - merge_requests

tests:
  extends: .test_template
  script:
    - npm run test:ci
  only:
    - merge_requests
