include:
  - project: 'smartive/ci-templates'
    ref: 4.x
    file: '/all-templates.yml'
  - project: 'smartive/ci-templates'
    ref: 4.x
    file: '/preview/default-preview-builds.yml'

stages:
  - build
  - deploy

build:
  extends: .gcb-docker
  stage: build
  variables:
    SUB_IMAGE: $REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy preview:
  stage: deploy
  variables:
    OPS_DIR: ./preview
    IMAGE_NAME: appimage
    IMAGE: $REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA

stop preview:
  stage: deploy

deploy production:
  stage: deploy
  extends: .gitops-update-image
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  environment:
    name: production
    url: https://smartive.ch
  variables:
    OPS_DIR: ./prd
    IMAGE_NAME: appimage
    IMAGE: $REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA
